### ISSUE TITLE
As a user, I want a seamless payment process when booking accommodations, dining reservations, transportation, and car rentals on the website

### ISSUE THREAD

**Issue by ramana22** [ramana22/TravelHub#7]
Estimation :
2 Points
**Acceptance Criteria:**

- 	Users are provided with secure payment options such as credit/debit cards or other relevant payment methods.
- 	The payment process is integrated into the booking flow for accommodations, dining reservations, transportation, and car rentals, ensuring a seamless user experience.
- 	Users can review and confirm their booking details before proceeding to the payment step.
- 	The system securely processes the payment transaction, encrypting sensitive information to protect user data.
- 	Upon successful payment completion, users receive confirmation of their booking via email or SMS, along with relevant booking details.
- 	In case of payment failure or errors, users are provided with clear instructions on how to resolve the issue, ensuring minimal disruption to the booking process.

**Comment by reshmavaase5** [comment]
done
